# ----------------------------------------------------------------------------
# Serveur web : port dédié au gateway
# ----------------------------------------------------------------------------
server:
  port: ${GATEWAY_SERVER_PORT:8089}

# gateway-service.yml (config-repo)

spring:
  application:
    name: gateway-service
  # ----------------------------------------------------------------------------
  # Configuration des routes Spring Cloud Gateway
  # ----------------------------------------------------------------------------
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1


    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: ${CORS_ALLOWED_ORIGINS:[]}
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - '*'
          allowCredentials: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - gateway
  access:
    default: none
  endpoint:
    gateway:
      access: unrestricted
