# gateway-service.yml (config-repo)

spring:
  application:
    name: gateway-service

  # ----------------------------------------------------------------------------
  # Serveur web : port dédié au gateway
  # ----------------------------------------------------------------------------
server:
  port: ${GATEWAY_SERVER_PORT:8089}

  # ----------------------------------------------------------------------------
  # Configuration des routes Spring Cloud Gateway
  # ----------------------------------------------------------------------------
cloud:
  gateway:
    routes:
      - id: account
        uri: lb://account-service
        predicates:
          - Path=/accounts/**
        filters:
          - StripPrefix=1


    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: ${CORS_ALLOWED_ORIGINS:[]}
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - '*'
          allowCredentials: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - gateway


